// Code generated by MockGen. DO NOT EDIT.
// Source: app_request_network.go
//
// Generated by this command:
//
//	mockgen -source=app_request_network.go -destination=./mocks/mock_app_request_network.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ids "github.com/ava-labs/avalanchego/ids"
	message "github.com/ava-labs/avalanchego/message"
	subnets "github.com/ava-labs/avalanchego/subnets"
	set "github.com/ava-labs/avalanchego/utils/set"
	peers "github.com/ava-labs/icm-services/peers"
	gomock "go.uber.org/mock/gomock"
)

// MockAppRequestNetwork is a mock of AppRequestNetwork interface.
type MockAppRequestNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockAppRequestNetworkMockRecorder
	isgomock struct{}
}

// MockAppRequestNetworkMockRecorder is the mock recorder for MockAppRequestNetwork.
type MockAppRequestNetworkMockRecorder struct {
	mock *MockAppRequestNetwork
}

// NewMockAppRequestNetwork creates a new mock instance.
func NewMockAppRequestNetwork(ctrl *gomock.Controller) *MockAppRequestNetwork {
	mock := &MockAppRequestNetwork{ctrl: ctrl}
	mock.recorder = &MockAppRequestNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRequestNetwork) EXPECT() *MockAppRequestNetworkMockRecorder {
	return m.recorder
}

// GetCanonicalValidators mocks base method.
func (m *MockAppRequestNetwork) GetCanonicalValidators(ctx context.Context, subnetID ids.ID, skipCache bool, pchainHeight uint64) (*peers.CanonicalValidators, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCanonicalValidators", ctx, subnetID, skipCache, pchainHeight)
	ret0, _ := ret[0].(*peers.CanonicalValidators)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCanonicalValidators indicates an expected call of GetCanonicalValidators.
func (mr *MockAppRequestNetworkMockRecorder) GetCanonicalValidators(ctx, subnetID, skipCache, pchainHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCanonicalValidators", reflect.TypeOf((*MockAppRequestNetwork)(nil).GetCanonicalValidators), ctx, subnetID, skipCache, pchainHeight)
}

// GetSubnetID mocks base method.
func (m *MockAppRequestNetwork) GetSubnetID(ctx context.Context, blockchainID ids.ID) (ids.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetID", ctx, blockchainID)
	ret0, _ := ret[0].(ids.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetID indicates an expected call of GetSubnetID.
func (mr *MockAppRequestNetworkMockRecorder) GetSubnetID(ctx, blockchainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetID", reflect.TypeOf((*MockAppRequestNetwork)(nil).GetSubnetID), ctx, blockchainID)
}

// IsGraniteActivated mocks base method.
func (m *MockAppRequestNetwork) IsGraniteActivated() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGraniteActivated")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsGraniteActivated indicates an expected call of IsGraniteActivated.
func (mr *MockAppRequestNetworkMockRecorder) IsGraniteActivated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGraniteActivated", reflect.TypeOf((*MockAppRequestNetwork)(nil).IsGraniteActivated))
}

// RegisterAppRequest mocks base method.
func (m *MockAppRequestNetwork) RegisterAppRequest(requestID ids.RequestID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterAppRequest", requestID)
}

// RegisterAppRequest indicates an expected call of RegisterAppRequest.
func (mr *MockAppRequestNetworkMockRecorder) RegisterAppRequest(requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAppRequest", reflect.TypeOf((*MockAppRequestNetwork)(nil).RegisterAppRequest), requestID)
}

// RegisterRequestID mocks base method.
func (m *MockAppRequestNetwork) RegisterRequestID(requestID uint32, requestedNodes set.Set[ids.NodeID]) chan message.InboundMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRequestID", requestID, requestedNodes)
	ret0, _ := ret[0].(chan message.InboundMessage)
	return ret0
}

// RegisterRequestID indicates an expected call of RegisterRequestID.
func (mr *MockAppRequestNetworkMockRecorder) RegisterRequestID(requestID, requestedNodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRequestID", reflect.TypeOf((*MockAppRequestNetwork)(nil).RegisterRequestID), requestID, requestedNodes)
}

// Send mocks base method.
func (m *MockAppRequestNetwork) Send(msg message.OutboundMessage, nodeIDs set.Set[ids.NodeID], subnetID ids.ID, allower subnets.Allower) set.Set[ids.NodeID] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", msg, nodeIDs, subnetID, allower)
	ret0, _ := ret[0].(set.Set[ids.NodeID])
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockAppRequestNetworkMockRecorder) Send(msg, nodeIDs, subnetID, allower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAppRequestNetwork)(nil).Send), msg, nodeIDs, subnetID, allower)
}

// Shutdown mocks base method.
func (m *MockAppRequestNetwork) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockAppRequestNetworkMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockAppRequestNetwork)(nil).Shutdown))
}

// StartCacheValidatorSets mocks base method.
func (m *MockAppRequestNetwork) StartCacheValidatorSets(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartCacheValidatorSets", ctx)
}

// StartCacheValidatorSets indicates an expected call of StartCacheValidatorSets.
func (mr *MockAppRequestNetworkMockRecorder) StartCacheValidatorSets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCacheValidatorSets", reflect.TypeOf((*MockAppRequestNetwork)(nil).StartCacheValidatorSets), ctx)
}

// TrackSubnet mocks base method.
func (m *MockAppRequestNetwork) TrackSubnet(ctx context.Context, subnetID ids.ID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackSubnet", ctx, subnetID)
}

// TrackSubnet indicates an expected call of TrackSubnet.
func (mr *MockAppRequestNetworkMockRecorder) TrackSubnet(ctx, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackSubnet", reflect.TypeOf((*MockAppRequestNetwork)(nil).TrackSubnet), ctx, subnetID)
}
