version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - whitespace

  settings:
    govet:
      disable:
        - shadow
    gocyclo:
      min-complexity: 20
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 160
    funlen:
      lines: 150
      statements: 80
    gosec:
      excludes:
        - G115

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - unparam
        text: "is always nil"

run:
  timeout: 5m
